-- MySQL Script generated by MySQL Workbench
-- Wed May  5 14:57:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cine
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `db_cine` DEFAULT CHARACTER SET utf8 ;
USE `db_cine` ;

-- -----------------------------------------------------
-- Table `db_cine`.`TBL_Taquilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cine`.`TBL_Taquilla` (
  `idTaquilla` INT NOT NULL AUTO_INCREMENT,
  `Sala` VARCHAR(45) NULL,
  `Butakas` VARCHAR(45) NULL,
  `Boletos` VARCHAR(45) NULL,
  `Precio` VARCHAR(45) NULL,
  PRIMARY KEY (`idTaquilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cine`.`TBL_Menú`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cine`.`TBL_Menú` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cine`.`TBL_Cartelera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cine`.`TBL_Cartelera` (
  `id_Cartelera` INT NOT NULL AUTO_INCREMENT,
  `PELICULA` VARCHAR(100) NULL,
  `HORA` VARCHAR(60) NULL,
  `FECHA` VARCHAR(100) NULL,
  `IDIOMA` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Cartelera`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
